import { Currency } from "@/types/currency";

export const currencies: Currency[] = [
  { code: "USD", name: "US Dollar", symbol: "$" },
  { code: "EUR", name: "Euro", symbol: "€" },
  { code: "GBP", name: "British Pound", symbol: "£" },
  { code: "JPY", name: "Japanese Yen", symbol: "¥" },
  { code: "CAD", name: "Canadian Dollar", symbol: "C$" },
  { code: "AUD", name: "Australian Dollar", symbol: "A$" },
  { code: "CHF", name: "Swiss Franc", symbol: "CHF" },
  { code: "CNY", name: "Chinese Yuan", symbol: "¥" },
  { code: "INR", name: "Indian Rupee", symbol: "₹" },
  { code: "BRL", name: "Brazilian Real", symbol: "R$" },
  { code: "RUB", name: "Russian Ruble", symbol: "₽" },
  { code: "KRW", name: "South Korean Won", symbol: "₩" },
  { code: "MXN", name: "Mexican Peso", symbol: "$" },
  { code: "SGD", name: "Singapore Dollar", symbol: "S$" },
  { code: "HKD", name: "Hong Kong Dollar", symbol: "HK$" },
  { code: "NZD", name: "New Zealand Dollar", symbol: "NZ$" },
  { code: "SEK", name: "Swedish Krona", symbol: "kr" },
  { code: "NOK", name: "Norwegian Krone", symbol: "kr" },
  { code: "DKK", name: "Danish Krone", symbol: "kr" },
  { code: "PLN", name: "Polish Złoty", symbol: "zł" },
  { code: "TRY", name: "Turkish Lira", symbol: "₺" },
  { code: "ZAR", name: "South African Rand", symbol: "R" },
  { code: "THB", name: "Thai Baht", symbol: "฿" },
  { code: "MYR", name: "Malaysian Ringgit", symbol: "RM" },
  { code: "IDR", name: "Indonesian Rupiah", symbol: "Rp" },
  { code: "PHP", name: "Philippine Peso", symbol: "₱" },
  { code: "VND", name: "Vietnamese Dong", symbol: "₫" },
  { code: "EGP", name: "Egyptian Pound", symbol: "E£" },
  { code: "NGN", name: "Nigerian Naira", symbol: "₦" },
  { code: "PKR", name: "Pakistani Rupee", symbol: "₨" },
  { code: "BDT", name: "Bangladeshi Taka", symbol: "৳" },
  { code: "LKR", name: "Sri Lankan Rupee", symbol: "Rs" },
  { code: "NPR", name: "Nepalese Rupee", symbol: "₨" },
  { code: "MMK", name: "Myanmar Kyat", symbol: "K" },
  { code: "KHR", name: "Cambodian Riel", symbol: "៛" },
  { code: "LAK", name: "Lao Kip", symbol: "₭" },
  { code: "MNT", name: "Mongolian Tugrik", symbol: "₮" },
  { code: "UZS", name: "Uzbekistani Som", symbol: "som" },
  { code: "KZT", name: "Kazakhstani Tenge", symbol: "₸" },
  { code: "GEL", name: "Georgian Lari", symbol: "₾" },
  { code: "AMD", name: "Armenian Dram", symbol: "֏" },
  { code: "AZN", name: "Azerbaijani Manat", symbol: "₼" },
  { code: "BYN", name: "Belarusian Ruble", symbol: "Br" },
  { code: "MDL", name: "Moldovan Leu", symbol: "L" },
  { code: "UAH", name: "Ukrainian Hryvnia", symbol: "₴" },
  { code: "RSD", name: "Serbian Dinar", symbol: "дин" },
  { code: "BGN", name: "Bulgarian Lev", symbol: "лв" },
  { code: "HRK", name: "Croatian Kuna", symbol: "kn" },
  { code: "CZK", name: "Czech Koruna", symbol: "Kč" },
  { code: "HUF", name: "Hungarian Forint", symbol: "Ft" },
  { code: "RON", name: "Romanian Leu", symbol: "lei" },
  { code: "ISK", name: "Icelandic Króna", symbol: "kr" },
  { code: "CLP", name: "Chilean Peso", symbol: "$" },
  { code: "COP", name: "Colombian Peso", symbol: "$" },
  { code: "ARS", name: "Argentine Peso", symbol: "$" },
  { code: "PEN", name: "Peruvian Sol", symbol: "S/" },
  { code: "UYU", name: "Uruguayan Peso", symbol: "$" },
  { code: "PYG", name: "Paraguayan Guaraní", symbol: "₲" },
  { code: "BOB", name: "Bolivian Boliviano", symbol: "Bs" },
  { code: "GTQ", name: "Guatemalan Quetzal", symbol: "Q" },
  { code: "HNL", name: "Honduran Lempira", symbol: "L" },
  { code: "NIO", name: "Nicaraguan Córdoba", symbol: "C$" },
  { code: "CRC", name: "Costa Rican Colón", symbol: "₡" },
  { code: "PAB", name: "Panamanian Balboa", symbol: "B/." },
  { code: "DOP", name: "Dominican Peso", symbol: "$" },
  { code: "JMD", name: "Jamaican Dollar", symbol: "$" },
  { code: "TTD", name: "Trinidad and Tobago Dollar", symbol: "$" },
  { code: "BBD", name: "Barbadian Dollar", symbol: "$" },
  { code: "XCD", name: "East Caribbean Dollar", symbol: "$" },
  { code: "BZD", name: "Belize Dollar", symbol: "$" },
  { code: "GYD", name: "Guyanese Dollar", symbol: "$" },
  { code: "SRD", name: "Surinamese Dollar", symbol: "$" },
  { code: "BWP", name: "Botswana Pula", symbol: "P" },
  { code: "ZMW", name: "Zambian Kwacha", symbol: "K" },
  { code: "ZWL", name: "Zimbabwean Dollar", symbol: "$" },
  { code: "NAD", name: "Namibian Dollar", symbol: "$" },
  { code: "LSL", name: "Lesotho Loti", symbol: "L" },
  { code: "SZL", name: "Eswatini Lilangeni", symbol: "L" },
  { code: "MUR", name: "Mauritian Rupee", symbol: "₨" },
  { code: "SCR", name: "Seychellois Rupee", symbol: "₨" },
  { code: "MVR", name: "Maldivian Rufiyaa", symbol: "Rf" },
  { code: "CVE", name: "Cape Verdean Escudo", symbol: "$" },
  { code: "GMD", name: "Gambian Dalasi", symbol: "D" },
  { code: "GHS", name: "Ghanaian Cedi", symbol: "₵" },
  { code: "XOF", name: "West African CFA Franc", symbol: "CFA" },
  { code: "XAF", name: "Central African CFA Franc", symbol: "FCFA" },
  { code: "XPF", name: "CFP Franc", symbol: "₣" },
  { code: "KMF", name: "Comorian Franc", symbol: "CF" },
  { code: "DJF", name: "Djiboutian Franc", symbol: "Fdj" },
  { code: "ETB", name: "Ethiopian Birr", symbol: "Br" },
  { code: "KES", name: "Kenyan Shilling", symbol: "KSh" },
  { code: "TZS", name: "Tanzanian Shilling", symbol: "TSh" },
  { code: "UGX", name: "Ugandan Shilling", symbol: "USh" },
  { code: "RWF", name: "Rwandan Franc", symbol: "FRw" },
  { code: "BIF", name: "Burundian Franc", symbol: "FBu" },
  { code: "MWK", name: "Malawian Kwacha", symbol: "MK" },
  { code: "ZMK", name: "Zambian Kwacha", symbol: "ZK" },
  { code: "AOA", name: "Angolan Kwanza", symbol: "Kz" },
  { code: "MZN", name: "Mozambican Metical", symbol: "MT" },
  { code: "STD", name: "São Tomé and Príncipe Dobra", symbol: "Db" },
  { code: "CDF", name: "Congolese Franc", symbol: "FC" },
  { code: "GNF", name: "Guinean Franc", symbol: "FG" },
  { code: "SLL", name: "Sierra Leonean Leone", symbol: "Le" },
  { code: "LRD", name: "Liberian Dollar", symbol: "$" },
  { code: "SLE", name: "Sierra Leonean Leone", symbol: "Le" },
  { code: "SSP", name: "South Sudanese Pound", symbol: "£" },
  { code: "SDG", name: "Sudanese Pound", symbol: "ج.س" },
  { code: "LYD", name: "Libyan Dinar", symbol: "ل.د" },
  { code: "TND", name: "Tunisian Dinar", symbol: "د.ت" },
  { code: "MAD", name: "Moroccan Dirham", symbol: "د.م." },
  { code: "DZD", name: "Algerian Dinar", symbol: "د.ج" },
  { code: "MRO", name: "Mauritanian Ouguiya", symbol: "UM" },
  { code: "XOF", name: "West African CFA Franc", symbol: "CFA" },
  { code: "XAF", name: "Central African CFA Franc", symbol: "FCFA" },
  { code: "XPF", name: "CFP Franc", symbol: "₣" },
  { code: "KMF", name: "Comorian Franc", symbol: "CF" },
  { code: "DJF", name: "Djiboutian Franc", symbol: "Fdj" },
  { code: "ETB", name: "Ethiopian Birr", symbol: "Br" },
  { code: "KES", name: "Kenyan Shilling", symbol: "KSh" },
  { code: "TZS", name: "Tanzanian Shilling", symbol: "TSh" },
  { code: "UGX", name: "Ugandan Shilling", symbol: "USh" },
  { code: "RWF", name: "Rwandan Franc", symbol: "FRw" },
  { code: "BIF", name: "Burundian Franc", symbol: "FBu" },
  { code: "MWK", name: "Malawian Kwacha", symbol: "MK" },
  { code: "ZMK", name: "Zambian Kwacha", symbol: "ZK" },
  { code: "AOA", name: "Angolan Kwanza", symbol: "Kz" },
  { code: "MZN", name: "Mozambican Metical", symbol: "MT" },
  { code: "STD", name: "São Tomé and Príncipe Dobra", symbol: "Db" },
  { code: "CDF", name: "Congolese Franc", symbol: "FC" },
  { code: "GNF", name: "Guinean Franc", symbol: "FG" },
  { code: "SLL", name: "Sierra Leonean Leone", symbol: "Le" },
  { code: "LRD", name: "Liberian Dollar", symbol: "$" },
  { code: "SLE", name: "Sierra Leonean Leone", symbol: "Le" },
  { code: "SSP", name: "South Sudanese Pound", symbol: "£" },
  { code: "SDG", name: "Sudanese Pound", symbol: "ج.س" },
  { code: "LYD", name: "Libyan Dinar", symbol: "ل.د" },
  { code: "TND", name: "Tunisian Dinar", symbol: "د.ت" },
  { code: "MAD", name: "Moroccan Dirham", symbol: "د.م." },
  { code: "DZD", name: "Algerian Dinar", symbol: "د.ج" },
  { code: "MRO", name: "Mauritanian Ouguiya", symbol: "UM" },
];
